version: '3'
services:
  mysql:
    image: mysql-account-db:latest
    build:
      context: ./MySQL
  
  account:
    image: account:latest
    build: 
      context: ./Account
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/account
    depends_on:
      - mysql
    ports: 
      - "9000:9000"

  eureka:
    image: eurekaserver:latest
    build:
      context: ./EurekaServer
    ports:
      - "8790:8790"

  web:
    image: web:latest
    build:
      context: ./WebService
    depends_on:
      - account
      - eureka
    environment:
      - server.account.host=account
      - server.account.port=9000
      - server.eureka.host=eureka
      - server.eureka.port=8790
    ports:
    - "80:8080"
